// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX9KgGelalIsQBSnaDAIYTI5zFY4iV1TM',
    appId: '1:561609644517:web:742032c247b62340ff770c',
    messagingSenderId: '561609644517',
    projectId: 'adminecommerce-f7336',
    authDomain: 'adminecommerce-f7336.firebaseapp.com',
    storageBucket: 'adminecommerce-f7336.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtIUWo9eL4DuFZqW6B3NZOQZO6lfP5k0E',
    appId: '1:561609644517:android:d4fe8b566bbc0e4eff770c',
    messagingSenderId: '561609644517',
    projectId: 'adminecommerce-f7336',
    storageBucket: 'adminecommerce-f7336.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGNi5N1LAfVxjrdORYSJbvuAz1maS6crA',
    appId: '1:561609644517:ios:9e592513e2c3943bff770c',
    messagingSenderId: '561609644517',
    projectId: 'adminecommerce-f7336',
    storageBucket: 'adminecommerce-f7336.appspot.com',
    iosBundleId: 'com.example.ecommerceadmin',
  );
}
